AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for Kittens Carousel Static Website on EC2.
  This template deploys Kittens Carousel Static website on Amazon Linux 2 EC2 Instance
  with custom security group allowing http connections on 80. Kittens Carousel Static
  Website is downloaded from GitHub repository, then deployed on Apache Web Server. 
Resources:
  MyWebServerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable HTTP for Apache Web Server and SSH for terminal
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  MyWebServerHost:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro
      KeyName: workshop_aws
      SecurityGroupIds:
        - !Ref MyWebServerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName} Stack
      UserData:
        Fn::Base64:
          !Sub |
            #! /bin/bash
            yum update -y
            yum install httpd -y
            cd /var/www/html/
            wget https://raw.githubusercontent.com/Mrt-Kom/MyProjects/master/101-kittens-carousel-static-website-ec2/static-web/index.html
            wget https://raw.githubusercontent.com/Mrt-Kom/MyProjects/master/101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
            wget https://raw.githubusercontent.com/Mrt-Kom/MyProjects/master/101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
            wget https://raw.githubusercontent.com/Mrt-Kom/MyProjects/master/101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
            systemctl start httpd
            systemctl enable httpd
Outputs: 
  WebSiteURL:
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt MyWebServerHost.PublicDnsName
    Description: Kittens Carousel Application URL
